// Моковые данные для отрисовки дизайна без бэкенда.
// Включаются только при VITE_USE_MOCKS=true (см. .env.example).
// Как только бэк отдаёт /api/tasks — этот файл можно удалить целиком.

const HOUR = 60 * 60 * 1000
const DAY = 24 * HOUR

function at(offset) {
  return new Date(Date.now() + offset).toISOString()
}

export const MOCK_TASKS = [
  {
    id: '1',
    title: 'Лабораторная работа №2',
    subject: 'Информатика',
    description:
      'Необходимо выполнить лабораторную работу по дисциплине «Информатика» и оформить отчёт в формате РЭУ. Работа включает теоретическую часть и практическое задание.',
    done: false,
    status: 'not_started',
    dueAt: at(4 * DAY + 14 * HOUR + 32 * 60 * 1000),
    xp: 100,
    icon: 'lab',
    reward: { name: 'Перо отличника', rarity: 'Редкий предмет' },
    tags: ['учёба'],
    source: 'max',
  },
  {
    id: '2',
    title: 'Эссе',
    subject: 'Философия',
    description:
      'Написать эссе на тему «Проблема свободы воли в современной философии». Объём — 1500–2000 слов, со списком литературы.',
    done: false,
    status: 'not_started',
    dueAt: at(6 * DAY + 9 * HOUR + 15 * 60 * 1000),
    xp: 80,
    icon: 'essay',
    reward: { name: 'Книга мудрости', rarity: 'Обычный предмет' },
    tags: ['письмо'],
    source: 'max',
  },
  {
    id: '3',
    title: 'Открытая встреча группы',
    subject: 'Политология',
    description:
      'Принять участие в открытой встрече группы, обсудить текущие вопросы и спланировать работу на следующую неделю.',
    done: false,
    status: 'not_started',
    dueAt: at(1 * DAY),
    xp: 50,
    icon: 'meeting',
    reward: { name: 'Медаль активиста', rarity: 'Обычный предмет' },
    tags: ['группа'],
    source: 'max',
  },
  {
    id: '4',
    title: 'Подготовка к экзамену',
    subject: 'Математика',
    description:
      'Повторить ключевые темы курса: линейная алгебра, математический анализ, теория вероятностей. Решить задачи из сборника.',
    done: false,
    status: 'not_started',
    dueAt: at(7 * DAY),
    xp: 150,
    icon: 'exam',
    reward: { name: 'Корона знаний', rarity: 'Эпический предмет' },
    tags: ['экзамен'],
    source: 'max',
  },
  {
    id: '5',
    title: 'Лабораторная работа №1',
    subject: 'Информатика',
    description: 'Выполнить первую лабораторную работу по информатике.',
    done: true,
    status: 'done',
    dueAt: at(-2 * DAY),
    xp: 100,
    icon: 'lab',
    reward: { name: 'Перо отличника', rarity: 'Редкий предмет' },
    tags: ['учёба'],
    source: 'max',
  },
  {
    id: '6',
    title: 'Реферат',
    subject: 'История',
    description: 'Написать реферат по истории России XIX века.',
    done: true,
    status: 'done',
    dueAt: at(-3 * DAY),
    xp: 60,
    icon: 'essay',
    reward: { name: 'Свиток историка', rarity: 'Обычный предмет' },
    tags: ['письмо'],
    source: 'max',
  },
  {
    id: '7',
    title: 'Тест по математике',
    subject: 'Математика',
    description: 'Пройти тест по теме «Производные».',
    done: true,
    status: 'done',
    dueAt: at(-4 * DAY),
    xp: 40,
    icon: 'test',
    reward: { name: 'Значок отличника', rarity: 'Обычный предмет' },
    tags: ['тест'],
    source: 'max',
  },
  {
    id: '8',
    title: 'Презентация',
    subject: 'Информатика',
    description: 'Подготовить презентацию по теме «Базы данных».',
    done: true,
    status: 'done',
    dueAt: at(-5 * DAY),
    xp: 90,
    icon: 'presentation',
    reward: { name: 'Кристалл оратора', rarity: 'Редкий предмет' },
    tags: ['проект'],
    source: 'max',
  },
  {
    id: '9',
    title: 'Контрольная работа',
    subject: 'Физика',
    description: 'Написать контрольную работу по механике.',
    done: true,
    status: 'done',
    dueAt: at(-6 * DAY),
    xp: 120,
    icon: 'test',
    reward: { name: 'Молот физика', rarity: 'Эпический предмет' },
    tags: ['контрольная'],
    source: 'max',
  },
  {
    id: '10',
    title: 'Доклад',
    subject: 'Литература',
    description: 'Подготовить доклад по творчеству А.С. Пушкина.',
    done: true,
    status: 'done',
    dueAt: at(-7 * DAY),
    xp: 70,
    icon: 'essay',
    reward: { name: 'Перо поэта', rarity: 'Редкий предмет' },
    tags: ['доклад'],
    source: 'max',
  },
  {
    id: '11',
    title: 'Практическая работа',
    subject: 'Химия',
    description: 'Выполнить практическую работу по органической химии.',
    done: true,
    status: 'done',
    dueAt: at(-8 * DAY),
    xp: 85,
    icon: 'practice',
    reward: { name: 'Колба алхимика', rarity: 'Обычный предмет' },
    tags: ['практика'],
    source: 'max',
  },
  {
    id: '12',
    title: 'Семинар',
    subject: 'Экономика',
    description: 'Принять участие в семинаре по микроэкономике.',
    done: true,
    status: 'done',
    dueAt: at(-9 * DAY),
    xp: 55,
    icon: 'seminar',
    reward: { name: 'Монета экономиста', rarity: 'Обычный предмет' },
    tags: ['семинар'],
    source: 'max',
  },
]

export const MOCK_USER = {
  name: 'Алексей И.',
  level: 7,
  xp: 320,
  xpToNext: 500,
  characteristics: [
    { key: 'int', label: 'INT', value: 42, icon: 'book' },
    { key: 'end', label: 'ЭНД', value: 35, icon: 'lightning' },
    { key: 'rep', label: 'РЕП', value: 28, icon: 'people' },
  ],
  group: {
    name: 'ИТ-21',
    members: 28,
    progress: 66,
  },
}

export const MOCK_STATS = {
  doneTotal: 34,
  streak: 6,
  onTime: 88,
  perWeek: 7,
  guildProgress: 64,
  level: 7,
  xp: 320,
  xpToNext: 500,
}
